//
//  JSControlEngine.h
//  Let
//
//  Created by junjie.zhu on 16/8/22.
//  Copyright © 2016年 BroadLink Co., Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <JavaScriptCore/JavaScriptCore.h>
#import "BLLet.h"

@interface BLJSControlEngine : NSObject

+ (instancetype)startEngine;

/**
 *  Evaluate a string of JavaScript code. Call it after +startEngine.
 *
 *  @param script A string containing the JavaScript code to evaluate.
 *
 *  @return The last value generated by the script.
 */
- (JSValue *)evaluateScript:(NSString *)script;


/**
 *  Get JS Context
 *
 *  @return context
 */
- (JSContext *)context;

@end
